### ISSUE TITLE
thaumcraft : Automagy

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#102]
Nécessaire ou pas? A premiere vu .. ca me semble vraiment pas mal :)

**Comment by sylphio** [comment]
21 infustion plus tard... sérieux.. ca prendrais un moyen d'automatiser....

Est-ce que witching gadget contient un item qui permet d'automatiser l'infustion crafting!
Si non, est-ce que automagy est équilibrer?

**Comment by rem0te** [comment]
Tu peu piper les item dans les pedestal (avec un hopper aussi ca marche), alors si tu peu preparer la recette et ta un system de logique pour distribuer les item au bon pedestal, tu peu.  Ca s'automatise tres bien avec ComputerCraft, alors ca doit ce faire avec OpenComputer.  La partie la plus toucher c'est de dealer avec les instabiliter

**Comment by sylphio** [comment]
Bonne idée le hopper.. ça pourrait marcher :) .. surtout que le type des items as aucune importance seul la géométries compte.  Reste que tu doit rester a coter pour right-clicker sur la matrix. Lors du right click, TC vérifie si tu as la recherche de débloquer.. donc un continous activator suffit pas :/

instabilité wise .. pas de problème, si mes calculs sont bon, ma table est capable de dealer avec des instabilité de + de 15 et la pire recette que j'ai trouvé ces ~10 .. donc devrais être bon :p tant que le crafting "jam" en court d'infusion ce qui cause de l'instabilité a la pelle.

C'est de devoir resté a coté pour right-cliquer avec le wand que je trouve un peu agaçant :/

**Comment by sylphio** [comment]
je me rend a l'opinion de rem. pas requis :)
