### ISSUE TITLE
OpenModularTurrets

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#108]
Completement inutile.. juste l'air drole!

**Comment by rem0te** [comment]
Ca fait quoi, ta un lien vers le wiki?

**Comment by sylphio** [comment]
En gros.. ca permet de mettre de tourelle qui tire sur ce que tu veut.
La documentation est ingame et utilise in-game wiki (IGW)  mais IGW était tellement merdique que je l'ai pas mis.

Donc en gros, non j'ai pas de lien mais sa semble pas très compliquer et leur tooltips nei est bien détailler.

**Comment by sylphio** [comment]
Autrement done ;p

**Comment by sylphio** [comment]
https://github.com/OpenModularTurretsTeam/OpenModularTurrets

https://www.youtube.com/watch?v=q1okKFXO-GA
