### ISSUE TITLE
[Ajout] Botania est-il toujour considerer?

### ISSUE THREAD

**Issue by rem0te** [sylphio/Sebcyn-MC-issues#111]
http://botaniamod.net/

**Comment by sylphio** [comment]
c'est pas super-heavy-worldgen based?

**Comment by sylphio** [comment]
a la 2e vue.. j'avoue que ca l'air hot et different de ce qu'On gosse d'habitude!

**Comment by rem0te** [comment]
En fait, ya moyen de spawner les fleurs post world gen avec de l'engrais,
et tout est baser sur les fleurs.

**Comment by sylphio** [comment]
Ca l'air cute. Coté équilibrage ça du sens ne serait-ce qu'un peu?

**Comment by rem0te** [comment]
Honnetement, je connais juste ce que j'ai vue dans les letsplay, mais ca
semble comparable a Thaumcraft

https://www.reddit.com/r/Thaumcraft/comments/32a77t/how_balanced_is_botania_with_thaumcraft/

Apparament il y a une synergy entre les 2 avec Forbiden Magic
http://thaumcraft-4.wikia.com/wiki/Add-ons#Forbidden_Magic_.28W.I.P_but_functional.29

Je sais qu'il y a un end game (genre, loin dans le tech path) qui permet de voler, un tiara (Bauble) alors faudra voir ce qui peu etre configurer

**Comment by sylphio** [comment]
Ça l'air équilibré. Y semble avoir une patch pour sphax (totalement requise pour tout ce qui est worldgen). Et je peut probablement faire de quoi pour les items qui volent.

Pour moi ce serait okay mais vu que c'est quand même un mod majeure (bien plus que mes turrets a 3 blocs) je propose qu'on fasse un petit sondage sur FB avant.

**Comment by sylphio** [comment]
Pourrait être intéressant si je réussisait a poussé le worldgen sur une autre planete/dimension ou qqch du genre!

**Comment by rem0te** [comment]
Mais totallement inutile.  Ya juste les fleurs dans le world gen, et on peu
les spawner avec un bonemeal special (bone meal + 2 rose red + 2 dandelion
yellow)

**Comment by sylphio** [comment]
k oublie ca pour un autre dimension.. :)

**Comment by sylphio** [comment]
Done. Juste Déactiver la flûgel thiara
