### ISSUE TITLE
Corporea de botania?

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#114]
@rem0te  salut,  je suis tomber la dessus et je me demandais si on rentrait ça dans la catégorie téléportation ou si c'était plus limité que ca? ton avis?

**Comment by sylphio** [comment]
On peut comparé a un pipe de TE.. ca donne une bonne idée.

**Comment by rem0te** [comment]
J'ai pas essayée donc je sais pas, mais j'ai lu la description
attentivement et ça à l'air quand même asser limiter
