### ISSUE TITLE
BC quarry bug

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#15]

**Comment by sylphio** [comment]
A retesté avec BC 6.3.3.

**Comment by sylphio** [comment]
La ender quarry semble une excellent alternative low-lag

**Comment by rem0te** [comment]
curieux que tu le sugere, ca pas mal le plus OP des quarry que je connaise.

**Comment by sylphio** [comment]
c'est le Low-Lag que j'aime bien ;P

**Comment by sylphio** [comment]
Fritz, as tu trouvé c'était quoi le bug finalement?

**Comment by sylphio** [comment]
Should be gone in 6.4
