### ISSUE TITLE
Activer Thaumcraft

### ISSUE THREAD

**Issue by MightyFritz** [sylphio/Sebcyn-MC-issues#17]

**Comment by rem0te** [comment]
+1  :P

**Comment by sylphio** [comment]
Dans 5 minutes si vous voulez.. mais en faites..  l'ajout de mods se résume simplement à cette question suivante auquel j'ai pas de réponse.

Quel est la meilleur façon de graduellement introduire les mods pour pas perdre complètement les newbies? Ils en arrachent déjà!
- Date fixe
- Quand tout le monde saura au moins se faire un macérateur, un basic power system et utilisé un pipe bluepower
- On s'en fout!

**Comment by MightyFritz** [comment]
A mon avis, ca depend du mod. Pour un mod comme GregTech qui vient changer drastiquement l'experience de base de Vanilla Minecraft, attendre est de mise (ou bien un serveur a part pour les joueurs plus hardcores). Pour des mods comme Thaumcraft ou OpenComputers, qui sont completement optionels, je ne pense pas que ca melangerais les newbies.
My 2 cents.

**Comment by sylphio** [comment]
Les mélanger... je ne pense pas ...  par contre les faire sentir encore plus larguer ça je pense que oui. On a la user base avec le plus gros écart de niveau qu'on a jamais eu donc pas évident de trouver le sweetspot.

TC est très nettement plus newbie friendly (pour les non-programmeurs) que open computer donc en compromis, je propose de remettre TC actif dans le courant de la semaine prochaine.

Ce que ça nous prendrais d'ici là par contre, c'est compléter la page wiki de TC pour y mettre quelque vidéos tutoriaux ainsi que quelque liens utiles.

(Fritz: sur une autre notes, j'ai déjà regardé la possibilité de faire 2 serveurs relié par une bungeecord (un portal interserveur) mais malheureusement c'est impossible avec un seul modpack (et donc, un seul config set). Les modifications de certains mods  (ex: gregtech) sont tellement extensive qu'ils ne peuvent pas être totalement déactivé quand on serait sur le server GT-free... Donc ça force 2 modpacks séparé et 2 serveurs auquel on connecte séparément. On obtiendrait vraiment une grosse fragmentation de notre déjà petite userbase.)

**Comment by MightyFritz** [comment]
Je m'occupe de mettre a jour le wiki, je connais quelques bons liens de wikis et aussi une series de tutoriaux sur youtube très détaillés.

**Comment by sylphio** [comment]
J'active TC4 à la première occasion!

**Comment by sylphio** [comment]
Done
