### ISSUE TITLE
Investiguer le spawn des slime pour les rendre plus accessible

### ISSUE THREAD

**Issue by rem0te** [sylphio/Sebcyn-MC-issues#21]
Autre option est d'ajouter une recette pour obtenir les slime ball de d'autre facon.
option A:  craft slime ball
option B:  craft slime spawn egg

sugestion d'item pour les craft:  IC2 resin, spider eye, egg, cactus...

**Comment by sylphio** [comment]
J'ai vérifié le code de JAS.. apparemment, il n’interfère pas avec le spawning des slimes.
Par contre, il fait rien pour les encouragés non plus.

Je continu d'investiguer.

**Comment by sylphio** [comment]
Suite a notre discutions de ce midi,on vas intégrer  le slimlizer de open Block dans le pack.

**Comment by sylphio** [comment]
slimlizer soumis
