### ISSUE TITLE
Dynmap : C'est quoi ces blocs noir au sommet des montagnes???

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#24]

**Comment by rem0te** [comment]
quel montagne?  toute les montagne?   Rapidement comme ca:  Volcan (mais la c'est toute la montagne qui est noire),  Thaucraft obelisk,  Oil ?

**Comment by sylphio** [comment]
C'est un biome qui devrais pas être la de mo creature :/

j'ai bricolé vite fait un support dynmap. Je vais l'intégré ce soir!

**Comment by sylphio** [comment]
http://www.sylphid.ca/dynmap/?worldname=sebcynworld&mapname=surface&zoom=5&x=-8777&y=64&z=-2337

**Comment by sylphio** [comment]
Soumis un custom render! fixé
