### ISSUE TITLE
Remettre I:itemLifespan dans les config BC a un chiffre raisonable

### ISSUE THREAD

**Issue by rem0te** [sylphio/Sebcyn-MC-issues#26]
Le default c'est 1200 (1 minute) et ca me semble acceptable

**Comment by sylphio** [comment]
En effet.j'avais mis ce setting que pour les fillers qui s'en servent même pas Finalement .

**Comment by sylphio** [comment]
Lava a 30%?

**Comment by rem0te** [comment]
hmm, ouais, faudrait que ca sois au moin en ligne avec IC2

**Comment by sylphio** [comment]
Done : 

Lava & item
