### ISSUE TITLE
Nerfer les mob spawner?

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#27]
Vu l'énorme densité de mob spawner dans la map, Je peut probablement overrider les mobs spawners et leur donnée une durée de vie.... les transformants par le fait même en ressource non-renouvellable.

Proposition, a chaque X mobs spawner, le spawn delay augmente de 1... On obtient un mob spawner qui spawn de moins en moins vite.

**Comment by MightyFritz** [comment]
Il me semble que ca serait encore mieux si plutôt que de réduire le spawn rate des spawners, on réduisait le drop des créatures (xp et items). Comme ca la difficulté reste la même, mais la récompense diminue drastiquement avec le temps. Sinon, bien que d'un coté le spawner ne donne plus autant de récompense, la difficulté elle aussi diminue (vu le nombre moins élevé de mobs).
Si tu implémente ça, il faudrait probablement garder les spawners de blaze du nether intacts, étant donné la seule source "naturelle" de blaze rods.

**Comment by sylphio** [comment]
En effet, c'est une bonne idée aussi. 

Si tous les mobs de tout les mods envois bien l’évent forge de "drop Stuff" (c'est pas le cas pour beaucoup d’évent) alors on peut probablement tagger les mobs avec un NBT tag et l'intercepter au drop. Seul inconvénient, le "random" pour le drop est fait dans l'entités elle même. On changera pas chaque mobs, donc ça implique de calibré une probabilité d'annuler un drop réussi. C'est pas un gros problème.

Dans l'autre cas, si on ne change que le spawner mais qu'on met la regression assez lente (ou limite une régression exponentiel ) alors un spawner "dans la nature" restera quasi pleinement opérationnel parce que personne ne restera immobile à coté pendant des heures. Ceux qu'on reste longtemps a coté sont normalement dans un environnement contrôler.

**Comment by psychorat911** [comment]
je ne prône pas vraiment l'idée de nerfer les drops de créatures, parce que pour tout ceux qui ne farm pas continuellement les spawners de façon exagéré, le fait que les drops deviennent plus rare obligera à farmer les spawners de façon exagérer afin d'avoir les 2-3 drops désiré.

**Comment by sylphio** [comment]
En faites, ceux on veut nerfer c'est que les Mobs qui ont spawner depuis le bloc mob spawner et seulement après un certain Temps genre ralenti à partir de 8h et stop après 48h (temps actif,valeur au pif). En gros si ça marche, y a que ceux qui farm les spawners qui vont voir une différence.  l'idée c'est juste que un spawner use avec le temps Et ne sois pas éternel.

**Comment by sylphio** [comment]
Partie comme on est là.. ce serait un peu trop tard... mais je garde l'idée pour une autre fois :)
