### ISSUE TITLE
nerfer le charcoal

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#29]
A partir du prochain update, je suis capable de controller les burntime de tout les fuels incluant vanilla.
Je propose la configuration suivante: Si vous trouver ca unfair, faite moi signe!
                                                     Valeur proposer     // nom::valeur par défaut dans MC
furnace.setFuel(minecraft:coal:0,       2000);  //coal:1600
furnace.setFuel(minecraft:coal:1,        800);  //charcoal:1600 
furnace.setFuel(minecraft:coal_block,  20000);  //coal_block:16000

furnace.setFuel(ore:logWood,             300);  //Wood pure:300
furnace.setFuel(ore:plankWood,           150);  //toute planches:300
furnace.setFuel(ore:slabWood,             75);  //demi-planche:150
furnace.setFuel(ore:stickwood,            50);  //stick:100
furnace.setFuel(ore:treeSapling,         100);  //sapling:100

//furnace.setFuel(minecraft:blaze_rod,      0);  //blaze_rod:2400  
furnace.setFuel(minecraft:lava_bucket,   7000);  //Lava:20000

Je propose de nerfer les planches aussi parce que sinon, 1 wood -> 4 planche donc ce serait plus efficace que le charcoal.

**Comment by sylphio** [comment]
Ha oui, autrement, mon update est prêt. j'attend que votre avis sur le sujet avant de l'envoyer.
J'active TC4 dedans.

**Comment by MightyFritz** [comment]
Ça fait du sens pour ce qui est de privilégier les ressources non-renouvelables. Ça fait moins de sens pour maintenir une performance de serveur décente à long terme. En effet, le charcoal étant la seule source d'énergie renouvelable encore potable qui marche bien autant pour faire du RF que pour du EU, ca va prendre des constructions mécanisées encore plus grosses et compliquées qu'en ce moment. (Et pour avoir ma base a coté de Code_Herder & Dralic, je peux dire que la performance est déjà problématique...)

**Comment by sylphio** [comment]
1- Tu as pas tord mais d'un autre coté toute machines peut être scaler au pts de mettre le serveur a terre. C'est a nous de faire des machines raisonnables. La particularité ici, c'est que même sans mes changements sur le charcoal,  il est extrêmement difficile en début de partie d'obtenir d'avoir quasi-infini d'énergie avec une installation justement raisonnable.  Si l'objectif de tout le monde est que sa base fonctionne a 100% à base l'énergie renouvelable peut importe le scale requis au lieu de comme énergie d'appoint. Alors, c'est aller dans le sens contraire du concept et dans ce cas, oui, tu as raison et je suis même aussi bien de denerfé les solars/winds/etc pour donner de la variété... Je suis absolument pas contre, j'ai voulu créer un challenge supplémentaire mais on peut se remettre au solar flower si ça tente a tout le monde.

2- Sur un autres sujet, si tes voisins créer suffisamment de Lag pour te rendre la vie difficile dans ta base.. clairement, il faut amélioré ça d'une manière ou d'une autre ou encore scaler down.

**Comment by Code-Herder** [comment]
Je me demandais pq le coal ordinaire est nerfe autant que le charcoal? Ca pousse un peux de dire que c'est renouvelable non?

Aussi, on devait pas booster le fuel pour contrebalancer la chose?

**Comment by Code-Herder** [comment]
Et pour mettre le serveur a terre, de ce que je voyais en ce moment c'etait un probleme purement client. La machine est a off en ce moment, on va apporter les correctif pour arranger le problème.

**Comment by sylphio** [comment]
En faites, c'est déjà fait pour le fuel ( ;p  ) (Changelog Wiki)

Fuel: +40% sur ic2 et BC

Et vu que le scripts est pas claire, je le refait
Valeur actuelle (MC vanilla)  -> ma proposition
Coal : 1600 -> 2000 (+25%)
Charcoal: 1600 -> 800 (-50%)
Coal Block: 16000 -> 20000

Log : 300 -> 300
Plank : 300 -> 150
Slab : 150 -> 75
Stick: 100 -> 50
Sapling: 100 -> 50

Blaze rod : 2400->800
Lava: 20000 -> 7000

**Comment by Code-Herder** [comment]
Ah désolé, j'avais pas réaliser que c'était du code, j'ai juste lut ca comme une table ascii et la dernière colonne était le résultat.

**Comment by Code-Herder** [comment]
Je sais que c'est pas dans ce script la, mais est ce que le coal coke a ete tweaker aussi? Faudrait pas que le coal normale approche du coal coke.

**Comment by sylphio** [comment]
Le coke tourne a 3200.. y a de la marge en masse :)

**Comment by sylphio** [comment]
Done!
