### ISSUE TITLE
Trouver un remplacant pour Bluepower!

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#30]
Vu que ca marche mal... que ca crash, lag.. etc...

A l'oeil, je vois deux candidats!

Thermal expansion : Classique sans besoin de présentation
Pneumatic Craft: https://www.youtube.com/watch?v=7wlV65fYssc
?
?

**Comment by rem0te** [comment]
En quoi Pneumatic Craft est un remplacement de Bluepower?  c'est un mod complement unique avec ses propre mechanique.  Et en plus Pneumatic Craft functionne est des plante qui sont generer dans le world, alors ca demenderais un re-gen.

**Comment by rem0te** [comment]
Faudrait savoir ce que tu veux remplacer de BluePower pour commencer.  Si c'est juste le transport d'item pour automatiser un truc, je dirait EnderIO

**Comment by MightyFritz** [comment]
Project Red semble être un autre remplaçant potentiel, surtout pour remplacer les circuits. EnderIO est surtout cool pour le transport d'items, de fluides et de RF. Les deux ont mon vote.

**Comment by Code-Herder** [comment]
Bien moi les trucs que jaime de BP et que je voudrais dans un remplacement :
- Des pipes avec une destination pre choisie qui drop pas les items.
- remplacement des filters/obsidian pipe/block breaker/deployer.
- un equivalent red wire pcq cest vachement pratique ce machin.

**Comment by MightyFritz** [comment]
Buildcraft fait deja une bonne partie de ce que tu decris. Bon c sur que avec BC le challenge c de pas dropper des items, mais construit intelligement un piping avec BC peut donner presque les mêmes resultats que Blue Power. Project Red est un remplacement pour les logics gates et les cables de redstone. EnderIO propose un piping system sans drop d'items qui te permet ultimement de deplacer des items efficacement selon le pattenr désiré.

**Comment by Code-Herder** [comment]
Bien moi mon requierement premier etait de pas dropper les items, apres c'était juste une question d'atteindre la parité BC/BP en termes de capacité.

Je sais que Seb veut remettre des frames éventuellement, donc ca vaut probablement la peine de checker la compatibilité avec les déplacements pendant qu'on y est. Je prends un guess mais BC est probablement tjrs peux effectif dans ce domaine.

Honnêtement ce qui me rend vraiment triste c'est la mega tour de processing de charcoal qu'on a construit purement BP et l'usine de ore processing a coté qui est juste BP. En fait on utilise BC seulement quand on est absolument forcé pour les liquides. Donc notre base va être nuker par le changement. Ca serait bien de pas etre obligé de complètement refaire le layout du piping en plus si c'est du piping qui drop.

**Comment by sylphio** [comment]
bon point, en partant du principe que BP est crappy... qu'est-ce qu'on as besoin de remplacer?

**Comment by rem0te** [comment]
Open block a des replacement pour les block breaker, deployer, ect... de BP

**Comment by sylphio** [comment]
Suite à la discutions, j'ai l'impression qu'effectivement un remplaçant n'est effectivement pas nécessaire.
