### ISSUE TITLE
Chisel est dead : Passé a chisel-2 ??

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#31]
La derniere version crashs sur RC.. fix soon!

**Comment by sylphio** [comment]
Okay, more fun here.

Chisel 2 ajoute la diorite.. ce qui serait vraiment nice pour nos amateur de diorite.

Par contre, conflit avec mon petit mod bricoler block envy qui nous la donne.. et on veut pas 2 diorite. faudrait donc bidouillé le level.dat pour que les 2 ID clash pour convertir automatiquement a celui de chisel ou encore un remapping de tout les chunks.

Prévoir un certain downtime.

**Comment by MightyFritz** [comment]
Looks fun. Est-ce que les items dans les chests seraient convertis aussi?

**Comment by sylphio** [comment]
vu que c'est que des blocs id, pas mal sure que oui!

**Comment by sylphio** [comment]
Bug RC fixé, je peut tenter une conversion!

**Comment by sylphio** [comment]
plus compliqué que prévu... chipsel ne remplace pas tout les blocs de blockenvy.. il manque les stairs, le polished diorites et les slabs...
