### ISSUE TITLE
Wind generator

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#32]
Passé le wind generator de 100 eu/t a 50 eu/t

**Comment by MightyFritz** [comment]
Je trouve les winds generators assez bien balancés en ce moment, surtout qu'il faut continuellement remplacer l'helice, qui coute assez cher pour avoir une bonne efficacité, et en plus la force du vent n'est pas constante.
A titre d'exemple, avec une hélice en bois, j'ai obtenu 10-15 EU/t pendant 3 heures (à peu près 3 millions de EU). Pour obtenir une hélice plus resistante et légèrement plus efficace (un peu plus de EU/t) ca coute

**Comment by MightyFritz** [comment]
(accidentellement accroché le bouton closed pendant que je tapais)

... Ca coute 45 iron ingot, plutot cher payé. Pour atteindre jusqua 100 eu/t, l'hélice requiert une hélice de carbone et nécessite près de 300 coals et 9 steel.

Bref, avec des couts en matériaux de cette envergure, à repayer régulièrement, je pense que ca ne nécessite pas un rebalancement.

**Comment by rem0te** [comment]
Je suis de l'avis de Fritz, comme je l'ai dit ce midi:  ca coute deja trop cher en materiaux non renouvelable pour me seduire, alors je trouve certainement pas que ca prend un nerf de plus.

**Comment by sylphio** [comment]
En faites, le wind générateur était pas nerfer du tout par erreur, il était appeler kinetic dans le config et j'ai crue que c'était le générateur a click. j'ai changé le config hier en meme temps que je fixais le crash du server (BP agains) et avant de voir vos reponse.

Je fait quelque math et je vous reviens la dessus.

**Comment by sylphio** [comment]
Bon en faites.. c'est pas mal plus dééquilibrer que je pensais. 

Supposons que vous avez 288 coal de trop!! vous voulez veut en faire du EU.

1- Coal -> Generateur : 1440 KEU 
2- Coal -> Heater -> Stirling  : 1440 KEU

3- Coal -> Coke -> Generateur : 2300 KEU
4- Coal -> Coke -> Heater/Stirling : 2300 KEU

Bon, je suis motiver
5: Coal -> Coke -> Boiler low pressure -> turbine RC : 9216 KEU

Giga motiver (Estimer celle là)
6- Coal -> Coke -> Boiler low pressure -> turbine RC 
    + Creosole -> boiler -> turbine RC : 16128 KEU  (estimé) 
     (1.75x la solution 5 pour tenir compte de 1/2 bucket de creosote par coke (3200 heat + 4800/2) )

Ou encore.. autre option!!!! Juste 2 blocs.
7: Coal -> turbine de windmill en carbone : 86400 KEU 
(ceci tient compte de mon nerf de 50% de hier...)

Excluant mon nerf de hier, le windmill est  pratiquement 10x plus efficace que toute les autres méthodes pour convertir du coal en EU et pour quasi aucune complexité.

A mon avis.. ça prend un nerf encore plus sévère! votre avis?
(Toutes les mesures sont prise ingame avec les configs actuelles)

**Comment by MightyFritz** [comment]
Est-ce que tu tiens compte du fait que la force du vent est variable et rarement 100%? Je vais faire quelques tests SP de mon coté pour confirmer les chiffres théoriques.

**Comment by sylphio** [comment]
non mais j'ai tellement de marge...  si elle tourne 9.3% du temps c'est mieux que le double boiler au coke/creosote.

Roch proposait d'utiliser genre la recette du steel pour celle au carbone.

**Comment by sylphio** [comment]
de ce que j'ai vu, c'est presque 100% du temps que  ca marche.

Pour te donné une idée, le windmill default .. ça reviens a un coal par 5 minutes en produisant 100 eu/t....y rien qui vas jamais être assez bon.

**Comment by MightyFritz** [comment]
Ok, conclusion de mes tests pratiques:
Le carbon rotor dure a peu pres 168 heures. Sans le nerf, il output en moyenne 133 EU/t. En 1h40, il produit 16 000 kEU. Sur sa durée de vie totale, il produira environ 1 600 000 kEU.

Une stack de coal coke produit 2 880 kEU en 10m40s dans un boiler préchauffé de 3x3x4. Il produit 225 EU/t en moyenne. Pour 288 coal, ca fait un total d'environ 13 000 kEU. Sans le créosote, le wind generator produit 40% moins de EU/t, par contre au total il produira presque 125x plus d'énergie.

Si on compare avec les autres rotors:
Wood - 33 EU/t en moyenne, durre de vie de 3 heures (15 Wood + 1 iron), 7 128 kEU total
Iron - 66 EU/t en moyennem durée de vie de 24 heures (45 irons), 114 048 kEU total
Steel - 100 EU/t en moyenne, durée de vie de 48 heures (45 steel), 345 600 kEU total
Carbon - 133 EU/t en moyenne, durée de vie de 168 heures (288 coal + 9 steel) 1 608 768 kEU total

Après avoir vu ces chiffres, qu'est-ce que tu proposes?

Perso, je penche pour deux approches:
a) Une reduction à 10% de la puissance actuelle, ce qui voudrait dire l'output total pour le rotor de carbon serait quand même de 160 000 kEU, 12 fois plus que dans un boiler, par contre l'ouput ne serait que de 13 EU/t, seulement 6% de l'output d'un boiler 3x3x4 avec deux turbines. Le wooden rotor deviendrait quasi inutile (3 EU/t pendant 3 heures ca donne plus grand chose)
b) On élimine le carbon rotor complètement avec un nerf des autre turbines à 50% de la puissance actuelle. Le meilleur résultat reste le rotor de steel, qui outputerait 50 EU/t avec un total de 45 steel pour pour 48 heures. En comparaison, une turbine de railcraft dure 168 heures et output 200 EU/t pour un cout de 35 steel en réparation. Le boiler peut rouler au charcoal, qui est renouvelable, qui nécessite plus de challenge pour un output en EU/t 4.5 fois plus élevé, ce qui semble un bon compromis.

**Comment by sylphio** [comment]
J'ai déactivé le carbon blade. Reste a trouvé un nerf factor qui as de l'allure. Je vais essayé de calculer un ratio équivalent iron -> carbon en fonction de la densité par chunk.

**Comment by sylphio** [comment]
On continue maintenant avec l'étude du rotor en steel.

Bon, il peut y avoir jusqu'à 320 coal et 208 iron (excluant le poor ore) si qqun vide une chunk au grand complet. (je suppose que le taux de succes du worldgen est egale)

Donc si on regarde celui en steel, qui est actuellement nerfé de 50%.
Steel - 50 EU/t en moyenne, durée de vie de 48 heures (45 steel), 172 800 kEU total (valeur a fred/2)

Si on prend comme unité de conversion le temps de piochage...
45 steel = 69 coal (disont 100 pour tenir compte de la maceration + conversion en steel).

Avec deux boiler un solid + un au creosote pour 100 coke on obtient : 5600 KEU

J'en déduit donc que c'est 30x plus efficace de passé sont temps a cherché du fer spécifiquement  pour alimenter un windmill que de chercher du coal pour un boiler. Surement que le fer est plus utile que le coal... mais de la a compenser un facteur x30.

J'ai pas calculer mais a l’œil les 2 autres rotors sont quasiment aussi ridicule que le premier.
Wood, 33eu/t pour 1 iron pour 3h... ca fait genre 33 eu/t pour moins de 1 équivalent coal a l'heure.

Perso, j’arrête de croire que ce bloc est récupérable. ma premier idée serait de limiter ce truc a un output ridicule comme les watermill ou encore grimper le cost en malade! Vous en pensez quoi?

**Comment by MightyFritz** [comment]
Comparons à un autre truc, pour mettre sur la table une autre perspective: le nucleaire. Selon mes calculs hautement scientifiques, le meilleur output possible d'un ore d'uranium, en comptant le fait que l'uranium peut etre re-processé plusieurs fois, est de 145 000 kEU. Selon les calculs plus haut, avec le nerf de 50% actuel, le steel rotor donne 7 500 kEU par iron ore. Je calcule environ 4 ores d'uranium en moyenne par chunk, ce qui donne un potentiel énergétique de 580 000 kEU par chunk en nucléaire. Dans mon test SP, j'ai trouvé 64 iron dans un chunk, alors je sais pas d'ou tu sort le 208 irons... (3 fois plus?), ce qui donne 70 000 kEU. Un réacteur nucléaire bien designé a donc beaucoup plus de potentiel que le wind generator fait de steel.

Un autre truc en comparaison: du charcoal dans un boiler. Le charcoal est une source d'énergie renouvelable, et avec assez de temps et de matériaux, on peut faire un tree farm qui peut alimenter une turbine qui fournit 200 EU/t pour une semaine à un cout de 99 steel pour le rotor. Le wind generator avec un rotor fait de 45 steel done (avec le nerf de 50%) donne 50 EU/t pour 2 jours. Le boiler qui roule au charcoal est donc 6.4 fois plus efficace en comparant le cout des rotors.

Ma conclusion: utiliser du coal coke dans un boiler n'est pas efficace, et seulement une solution en début de partie, lorsque le cout des autres solutions est encore trop élevée en matériaux. Oui, le wind generator donne une source d'énergie intéressante à faible cout, par contre c'est loin d'être la source d'énergie la plus efficace en cout de matériaux, ni la source qui produit la plus grande puissance de sortie.

**Comment by MightyFritz** [comment]
Legere correction: 64 irons ores dans un chunk donne 480 000 kEU total, donc relativement comparable au nuclaire.

**Comment by MightyFritz** [comment]
Autre correction, mes test montrent finalement 6 uraniums par chunk en moyenne, ce qui donne au final: 870 000 kEU en potentiel énergétique par chunk pour le nucléaire, 480 000 kEU par chunks pour utiliser des rotors de steel dans un wind generator.

**Comment by sylphio** [comment]
Pour mes values, j'ai pris les configs du générateurs. j'ai supposé un taux de succes de 100%. c'est trop élevé on average mais la proportion entre le coal et le iron est bonne et j'ai fait x2 pour le iron grâce au macérateur.

Autrement, as tu vu le setup que ca prend pour un nucléaire dans ic2? comparé au 2 bloc d'un windmill.... 

Vu le danger et la complexité.. un nucleaire devrais être waaaaaaay better qu'un windmill.

et avec tes propres chiffre, 870 Meu < 960 Meu (x2 mascerateur)

**Comment by MightyFritz** [comment]
Le macérateur est pris en consideration dans mes calculs aussi. Donc si je comprends mieux, il y aurait 104 iron ores dans un chunk en théorie, j'imagine que j'ai vu 64 à cause des caves et des blocs qui ne sont pas de la pierre, donc du 104 théorique ca fait du sens d'espérer 64 en pratique?

**Comment by sylphio** [comment]
64 en pratique.. ca doit pas être loin de ça.  mais je trouve quand même qu'on est vraiment pas loin du nucleaire. 
Au max dans une chunk, il y a 320 coal,  208 iron et j'ai malheureusement pas les chiffres pour l'uranium.

mais bon, en partant de tes chiffres... un windmill au steel = 55% d'une station d'enrichissement d'uranium, d'un reacteur, d'une steam turbine, d'un échangeur de heat.. d'une cooling station et d'un reprocessing plant pour l'uranium. .... heu...

**Comment by sylphio** [comment]
Perso, je vois le nucleaire comme le endgame "near infinite" energie plan. J'espère donc qu'il soit beaucoup mieux. Surtout que si on considère que la progression ic2 seul, le generateur et le heat/stinrling sont ~4x moins efficace que le boiler. 

Autrement, J'ai testé hier et je suis a 80% certain que le nucléaire fini par utilisé un kinetic dans sa chaine de production a vapeur. Par conséquent, je peut pas nerfé le wind sans toucher affecté les 2. Par conséquent, J'ai déactivé complètement tous les rotors de windmills.

**Comment by sylphio** [comment]
Fermé pour le moment mais ouvert à le remettre si on trouve un moyen de lui trouver un positionnement correcte.
