### ISSUE TITLE
Le mystère des poulets

### ISSUE THREAD

**Issue by psychorat911** [sylphio/Sebcyn-MC-issues#36]
nos poulets disparaissent lorsque situé sur notre chicken farm... Tout est éclairé et sont a l'intérieur et clôturé.

**Comment by sylphio** [comment]
je suis aller voir.. tout est normal! 
J'ai vérifé par commande le spawner, il me confirme que le despawn n'est pas autoriser dans ton enclos. 

Le plus probable, tu as rien de sécurisé autour et la "chasse" de mo creature est activé.
Je me demande si c'est pas une bestiole qui vas se taper tes poulets

**Comment by sylphio** [comment]
as tu une méthode pour reproduire le problème?

**Comment by sylphio** [comment]
Psychorat as fait sauté le spot!! fixed by destruction!
