### ISSUE TITLE
Les cables ic2 sont complètement sans perte.....

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#37]
Il y a une option dans le config ic2

; Use the new highly experimental current + voltage energy net model with energy loss.
; Only set this to true if you know what you are doing.
useLinearTransferModel = false

Ca pourrait etre fun de mettre ça a true si leur truc marche un peu.

**Comment by MightyFritz** [comment]
Avant de publier, faudra quelques jours de notification, juste au cas où il y aurait des risques d'explosion ou de autre.

**Comment by MightyFritz** [comment]
Aussi faudrait que la doc soit up to date...

**Comment by sylphio** [comment]
"théoriquement" les machines exploses pas encore..... ca nous laisserais une chance.. 

Coté doc, j'y crois pas trop! ça serait probablement a "tester"

**Comment by Code-Herder** [comment]
Je serais pour seulement si on a une facon quelconque de savoir comment ca marche ce machin sans lire le code. De ce que j'ai lut sur les forums c'est complètement différent du système de packet, c'est un autre système.

**Comment by sylphio** [comment]
Quelqu'un serait dispo pour investiguer ça?

**Comment by sylphio** [comment]
Pong!

**Comment by sylphio** [comment]
bof, dans le fond.. il est un peu tard pour ca :)

Ce sera pour une autre fois!
