### ISSUE TITLE
Remettre le kinetic generator par defaut

### ISSUE THREAD

**Issue by MightyFritz** [sylphio/Sebcyn-MC-issues#39]
Remettre l'efficacité du Kinetic generator à 1 pour que le steam generator soit éventuellement plus efficace que les générateurs standards

**Comment by sylphio** [comment]
Zut, en effet, j'ai oublié de le remettre a 1 en même temps que j'ai viré les windmills.

P.s Ma confiance en ic2 étant ce qu'elle est...  Comment se positionne le steam gen par rapport au boiler RC en terme d'efficacité? J'ai pas réussi a ajuster le steam génération comme du monde dans mon test single player.

.

**Comment by sylphio** [comment]
done
