### ISSUE TITLE
Plus de portes!

### ISSUE THREAD

**Issue by psychorat911** [sylphio/Sebcyn-MC-issues#42]
Je fais juste proposer un petit mod qui permet de faire des portes avec tout plein de type de blocks, et tout plein de solidité selon la même recette de base. Question entre autre d'avoir des portes d'obsidienne blastproofs  ou des portes en vitres...ou bien des portes de black oak couleur black oak...

C'est toujours bien plein  d'options!

Pour une petite idée de quoi ça a l'air.
http://bdcraft.net/forum/64x-extra-doors-151

**Comment by rem0te** [comment]
A tu essayer les carpenter door?   Je sais pas pour la durabiliter, mais sinon tu peu utilser n'importe lequel block pour la texture et ta le choix de plusieur model, ansi que determiner si elle agit comme une porte en bois ou une porte en metal.  

http://wiki.resonant-rise.com/view/Carpenter%27s_Door_%28Carpenter%27s_Blocks%29

**Comment by psychorat911** [comment]
carpenter fonctionne mais c'est purement estétique, et si tu click sur la porte avec quoi que ce soit dans les mains ca change la couleur me semble. Je proposait ça pour la variété et avoir d'autres option que la steel door comme porte qui barre ou que les zombi arrache pas.
...

**Comment by rem0te** [comment]
Premierement, les mob reconnaisse pas les porte carpenter, alors il peuve pas l'ouvrir.
Deuxiemement, en plus de changer la "couleur" avec les block, si tu rightclick avec le marteau, tu peu changer le look de la porte, et determiner si elle agis comme un porte en steel.
:)

**Comment by sylphio** [comment]
Toujours d'actualité ou pas?

**Comment by sylphio** [comment]
Toujours d'actualité?
