### ISSUE TITLE
Ic2 : Déactivate RTG generator! 

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#54]
je l'aurais nerfé un peu à place mais zero config et 16 eu/t a l'infini.. c'est beaucoup!

**Comment by MightyFritz** [comment]
Je suis pas d'accord pour nerfer le rtg. L'effort requis pour acquerir le combustible vaut la "récompense" de 16 EU/t. Ca prend 5x3x9 rods d'uranium dans un réacteur nucléaire pour parvenir à ce résultat, en plus du temps pour bruler tout ce combustible, en plus de la complexité et du cout du réacteur pour consommer cet uranium.

**Comment by MightyFritz** [comment]
Conparable à la création s'un tree farm avec moins de composantes (donc moins d'impact de perf) mais aussi moins efficace.

**Comment by rem0te** [comment]
Seb, ma etre affreusement franc:  arrete de vouloir tout "balancer" a grand coup de hache dans les features, pi prend plus de temps pour jouer a place.  Rendu la, deactive aussi le biodiesel parce que je fais deja 10 eu/t "a l'infinie" avec des feuille et des bout de cactus depuis la premiere semaine. ;)

**Comment by sylphio** [comment]
L'idée c'était de donner un coup de main au truc non-renouvellable ! 
Est-ce que c'était une bonne idée? Futile? Probablement, mais j'aurais au moins le mérite d'essayer de rendre le départ un peu plus intéressant que de simplement stacker des solars. 

p.s pour le RTG, j'ai simplement rendu la pellet un peu plus dispendieuse! Ca vas juste stacker un peu moins vite.
