### ISSUE TITLE
TC : Champion mob

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#56]
apparemment sont trop fort!!

Faire quelque test avec un nanoarmor et un tc shield.

**Comment by sylphio** [comment]
... tellement une impression de déjà vu avec infernal mobs...

**Comment by MightyFritz** [comment]
De mon coté je nai pas de problemes avec les champion mobs. Ils sont durs a cuire, mais loin d'etre au niveau de Infernal Mobs.

**Comment by rem0te** [comment]
indeed.  oui y font mal, mais c'est comme pas tres dure a tenir loin un zombie, et sont loin d'etre invincible:  j'ai tuer un warded zombie avec un wooden sword sans aucune armure sur le dos. (j'avais pas le choix je voulais recupere mon stock! ;) )

**Comment by sylphio** [comment]
Me suis amuser hier a provoquer quelque duel (donc un 3 contre moi)) et j'ai pas eu trop de misère en nano et en diamond armor.

De tout les champions, il  y en a 2-3 types qui semble dangereux (mighty, truc d'araignée) et le reste c'est quand même correct. Je considère normal que si je me ballade la nuit, je prend un risque.  Reste a voir si c'est correct aussi dans le nether.

Je suis ouvert à les déactivés complètement (la seul option) si c'est l'opinion de la majorité mais mon vote vas aller pour les garder.

**Comment by sylphio** [comment]
Azanor porte thaumcraft en 1.8.. TC est donc probablement en version finale de notre point de vu.

**Comment by sylphio** [comment]
Enfin quelques statistiques.

Un mod champion fait 3x plus de dommage que la version de base.
Un mod champion mighty fait 12x plus de dommage que la version de base.

(Les dommages sont en demi-coeur, un player as donc 20 hp)
Mighty Heat Spider : 36 (demi coeur) -> 3.6 full nano, 7.4 en full diamond
Mighty Pigman : 90 demi-coeur  -> 9 full nano, 18 en full diamond

Morale de l'histoire, si vous voyez un mighty.. sauver vous!

**Comment by psychorat911** [comment]
Le seul probleme c'est qu'il faut être à portée de frappe pour les identifier, on peut pas vraiment les prévoir a moins d'aller se coller le nez dessus et de prendre le temps de lire leur nom... ce qui mene à une mort certaine, considérant que la majorité des champions ont un range plus élevé que nous pour attaquer.

l'idé des champions est comique, mais s'ils n'avaient que leur habilité en plus et x3 pour les mighty... se serait parfait!  et pas de range d'attaque augmenter. Un mini mighty zombi qui frappe de plus loins et qui cours partout est une mort assuré et inevitable.

**Comment by sylphio** [comment]
Je laisse ouvert la possibilité de simplement ajouter un "max damage" dans sebcynmod pour nerfé un peu les champions mais en gros, je pense que l'opinion générale, c'est de les garder donc je close le issue.
