### ISSUE TITLE
Problème d'inventaire depuis ce matin

### ISSUE THREAD

**Issue by psychorat911** [sylphio/Sebcyn-MC-issues#57]
Probablement lié au mod de sorting pour l'inventaire qui est tout nouvellement ajouté, j'ai eu des troubles multiple et diverses: 
- Items qui changent de place ou se dupliquent dans l'inventaire (j'ai du placer 5 cubes de brique alors que j'en avait 2...et ils sont rester placés)
- Items qui disparaissent jusqu'à ce que j'ouvre un coffre
- quec truc bizzare de project table qui pile les item de la table avec les autre dans l'inventaire automatiquement...
- items qui se transformes en d'autres ou qui essaient de se stacker avec d'autres items semblables : 1 manual kinetic engine et 1 turning table -> 2 turning tables dans l'inventaire -> qui se sont changé en kinetics engines une fois placés au sol...

(j'oubliais) - 2 block d'iron chiselés differemments --> se sont fait stacker ou bien qquec chose du genre --> ensuite j'en place un et le deuxieme a disparu...

autre trouble recent probablment pas lié:
- quand je fait une recherche dans nei tout les cases d'inventaire deviennent noir et il est impossible de voir quoi que se soit sans enlever la recherche.

sinon, j'ai essayé de sorter l'inventaire de coffres pour finalement tout replacer a la mains 1 item a la fois après parce que c'était tout croche ;)

**Comment by sylphio** [comment]
Je vais déactivé tout les raccourcis pour tweak inventory.. de cette manière on le déclenchera que avec les boutons sur l'inventaires ;p

**Comment by sylphio** [comment]
Et je viens de réalisé que j'ai besoin d'installer un truc server side pour que ca marche bien!

**Comment by sylphio** [comment]
Ca devrait etre bon avec le dernier update! si c'est pas le cas, écrire un commentaire et je réouvrirai le bug.
