### ISSUE TITLE
Il est temps de remettre le mod de pierre tombale je pense!

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#59]
Je suis contre le fait de récupéré 100% de son stock quand on meurt par contre. Mourir doit être risquer.

Ce que j'avais bricolé sur le pack 3 marchais bien je trouve, les chances qu'un item se retrouve dans la tombe dépendait du slot dans lequel il était.

De mémoire, c'était genre 90% pour l'armure et les items de la hotbar et 50% pour le reste ou qqch dans le genre.

**Comment by sylphio** [comment]
J'ai retrouvé les pourcentages pour les tombes du pack 3.

Armures: 96% de chance que l'item se retrouve dans la tombe plutôt que de dropper au sol.
5 premiers slots du hotbar : 96%
4 derniers slot du Hotbar : 80%
Le reste de l'inventaire: 20%

Le pack 5 est quand même pas mal plus facile que le pack 3.

**Comment by sylphio** [comment]
Voilà ma proposition, si vous avez un meilleur algo, c'est le temps :)

Armures + 5 premiers slot du hotbar: 93% de chance pour chaque item qu'il se retrouve dans la tombe plutôt que de dropper au sol.
   Si ces 4+5 slots sont plein ~ 52% perdre rien, 35% perdre 1 items, 10% perdre 2 items.

4 derniers slot du hotbar: 90%
  ~ 65% perdre rien, 29% perdre 1 items, 4% perdre  2 items

Reste de l'inventaire.. 80%  
   En simulant que les 27 slots sont plein. ça donnerais entre 3 et 8 items perdus + 85% du temps.

**Comment by aksel120** [comment]
J'approuve mettre le mod pierre tombale il est tres bien

**Comment by sylphio** [comment]
L'option simple semble plaire a tout le monde. Armure + hotbar dans le body... le reste à terre

**Comment by sylphio** [comment]
Résumé de l'implémentation.

En cas de mort, L'armure, la hotbar et le baudle se retrouve dans le corps sans dommage.. le reste drop a terre. Le corps reste en place 24h avant de despawner.

Le corps est totalement indestructible SAUF AU FEU... mourir dans la lave sera toujours aussi terrible (ça fait "minecrafty").

Pour détruire un cadavre, enterrer-le avec une pelle.
