### ISSUE TITLE
Web : Mettre a jour la page web principale avec la liste de tout les mods

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#6]

**Comment by rem0te** [comment]
debloque la commande /dmarker pour qu'on puisse pourrir la map nous meme! :P

**Comment by rem0te** [comment]
Sois sur de metre l'info sur toute modification par raport au behavior normal

Et si ya moyen d'avoir notre propre "wiki" histoire de noter nos observation pour les mod mal documenter?

**Comment by sylphio** [comment]
excellent idée mais ho boy a mettre en place :/ 

je vais y penser

**Comment by sylphio** [comment]
plus j'y pense plus j'aime ton histoire de wiki remote

**Comment by rem0te** [comment]
ca a pas besoin d'etre fancer, juste un notepad qu'on peu editer.  ya peut-etre moyen avec google doc?

**Comment by sylphio** [comment]
Wiki en ligne

**Comment by sylphio** [comment]
bon.. c'est fait :)
