### ISSUE TITLE
Me faire déban plz

### ISSUE THREAD

**Issue by aksel120** [sylphio/Sebcyn-MC-issues#60]
Salut c'est aksel120 je suis l'ami de mathieu si vous le connaissais(en se connais irl aussi)est je veux me faire deban car j'ai envie de m'amuser sur le serveur avec tout les mods ect est aussi je ferai du thaumcraft(pro de thaumcraft) est si possible ajouter 2 mods de magie le premier(Ars magica 2) est le 2e(Witchery) merci est j'espere de vous revoir sur le serveur si je me fais déban a oui est je sais aussi pas pourquoi je me suis fais ban bon ben a+

Cordialement Aksel

**Comment by sylphio** [comment]
Salut Aksel,

Pour répondre à ta question, oui je connais bien Mathieu. Contrairement à ce que tu sembles croire, il n'y a aucun ban à ton endroit. C’est tout simplement que c'est un petit serveur privé utilisé seulement par moi et quelques amis proches. L'accès est que sur invitation.

Pour cette raison, je dois refuser ta demande, mais je te souhaite bonne chance dans ta quête de magie.

Sylphio
Administrateur
