### ISSUE TITLE
Enchantements Bluepower

### ISSUE THREAD

**Issue by psychorat911** [sylphio/Sebcyn-MC-issues#63]
Dernièrement la pluspart de mes tentatives d'enchantements finissent tous par une adresse du genre:

enchant/bluepower/disjunction... ou autre truc du genre au lieu de unbreakable,smite,sharpness ...

Est-ce que ça fait de quoi  ce truc? (il me semble qu'au début ça disait clairement  disjonction I-IV )

**Comment by sylphio** [comment]
disjunction : boost de dommage contre les endermans...

bon, quand a savoir si ça marche... comme tout ce qui touche BP..j'ai des doutes

**Comment by psychorat911** [comment]
na ce que je veux dire c'est que ça semble pas écrire disjunction, ca écrit  +- l'adresse d'un fichier... contrairement à tout les autres enchantements.

**Comment by sylphio** [comment]
devrais-je être surpris par un autre bug dans bluepower? ;p

**Comment by sylphio** [comment]
Probablement que c'Est le dernier update de BP qui a causé ça.

**Comment by sylphio** [comment]
@psychorat911  Est-ce que ca été réglé par l'update de BP?

**Comment by sylphio** [comment]
Cosmetique anyways!
