### ISSUE TITLE
Lycanite dans le nether!!

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#72]
(et peut etre dans une autre dimension overworld style?)

**Comment by rem0te** [comment]
Faudrait, parce que je vois pas vraiment les monstre de swamp dans le nether :P

**Comment by sylphio** [comment]
La seule chose qui me fait hésiter c'est que ce mod grossissait juste assez le modpack pour que ceux avec les pc les moins fort commence a avoir des problèmes. (Troll & drift).

**Comment by sylphio** [comment]
Comme je me doutais, et après les essais avec le texture pack. on vois que la taille du texture pack (et donc de l'atlas) as une énorme impact sur la performance des client. Lycanite grossirais le tex pack ~40 mo et ca nous ferais pas mal revenir en arrière :/

Donc je mets ça sur la glace :/
