### ISSUE TITLE
Zephyr sword qui se repare pas?

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#78]

**Comment by psychorat911** [comment]
hummmm yep enchant de thaumcraft "repair II" et ça semble pas fonctionner, me semble ça marchait avant (avril...).  Peut-être un ti conflit avec le repair de thinker?

**Comment by MightyFritz** [comment]
Pour pouvoir réparer, les items thaumcraft avec le enchant repair ont besoin de vis. Ca prend une baguette avec du vis dans l'inventaire ou bien une amulette de vis chargée.

**Comment by sylphio** [comment]
Fix
