### ISSUE TITLE
Config : Les ogres sont de retours avec le nouveau spawner. Que faire avec?

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#8]

**Comment by Dralic** [comment]
J'ai pas vraiment de préférence pour autant que je sache qu'ils sont la (je dois batir en conséquence)

**Comment by sylphio** [comment]
Option:
-Les exclures totalement
-Les rendres plus aveugles de manière a ce qu'il attaque pas 12 case au travers des murs
-Rendre les explosions moins violente de manières à ne détruire que la dirt et le sand.
-Empêcher leur coup d'endommager des blocs, ils redeviennent des mobs ordinaires.

**Comment by rem0te** [comment]
Mon gros probleme avec eu, ca a toujours ete leur pouvoir de destruction, alors option 3 (reduire) ou 4 (pas de destruction) me va tres bien.

**Comment by sylphio** [comment]
j'ai reduit leur pouvoir de destructions a zero pour les vert et les rouges. c'est ceux qui existe en surface.

J'ai gardé le pouvoir de destruction sur les bleus.. ça vous vas ou je déactive ceux la aussi?

**Comment by MightyFritz** [comment]
Perso je désactiverait seulement leur habilité a voir a travers les murs. Se faire surprendre par derrière, "it's part of the game", mais se faire démolir par un mob derrière un mur que tu n'as pas pu prévenir, ca c'est pas cool.

**Comment by sylphio** [comment]
Tu nerferait les bleus qui sont les seuls qui restes?

**Comment by MightyFritz** [comment]
A moitie: je garderais leur puissance devastatrice, mais je reduirais drastiquement leur abilite a voir a travers les murs.

**Comment by sylphio** [comment]
Je peut faire ça.. je vais reduire leur view distance de la moitié.. ça réduira leur couverture en surface d'un facteur x4.

**Comment by sylphio** [comment]
reduit a 6
