### ISSUE TITLE
Les ENT font du degat !?!

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#80]
Viens de me faire raser mon launchpad par une de ces bestioles :/

Le temps de pigé que ca prend une hache vanilla pour leur faire le moindre mal.

**Comment by psychorat911** [comment]
moi jles fou en feu, mais je ne les ai jamais vu attaquer quoi que se soit.

**Comment by sylphio** [comment]
Good to know. Ils démolissent en plantant des saplings ou des fleurs.

**Comment by sylphio** [comment]
Probablement acceptable comme dommage.  J'ai été plutôt surpris de le voir tout casser.

**Comment by sylphio** [comment]
bon, finalement, vu qu'il y a moyen de les détruires :).. close!
