### ISSUE TITLE
[Ajout] Quand on aura fini de faire le tour de l'existant : Art magica 2?

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#98]

**Comment by rem0te** [comment]
Ars Magica?  hmmm.  le concept de boss etais le fun, et le level + crafting de spell etais vraiment different.  J'aimais bien, mais je suis loin "d'avoir fait le tour" et mon feeling etais que AM2 etais pas mal dans le genre OP

**Comment by sylphio** [comment]
tout a fait d'accord sur l'ensemble de tes commentaires :)

Coté op-i-tude, surement un peu mais on est rendu quand même assez loin en tech que je pense pas  que ca changerais beaucoup la dynamique. C'est pas comme si c'était une fresh map. Viré le ultra-Op advanced miner aurais plus d'effet!

Je me souviens surtout que le crafting de spell était vraiment intéressant :).. beaucoup plus que TC.
